### ISSUE TITLE
Package Qt 5.11.1 can't be build using Visual Studio Community 2017 15.9.4

### ISSUE THREAD

**Issue by Mikalai** [ruslo/hunter#1702]
Error:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1271): error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior. [H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj]

Logs:

-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: H:/projects/hunter
-- [hunter] [ Hunter-ID: 36fbf68 | Toolchain-ID: 2413e11 | Config-ID: 3648706 ]
-- [hunter] QT_ROOT: H:/projects/hunter/_Base/36fbf68/2413e11/3648706/Install (ver.: 5.11.1)
-- [hunter] Building Qt (component: qtbase)
loading initial cache file H:/projects/hunter/_Base/36fbf68/2413e11/3648706/cache.cmake
loading initial cache file H:/projects/hunter/_Base/36fbf68/2413e11/3648706/Build/Qt/__qtbase/args.cmake
-- The C compiler identification is MSVC 19.16.27025.1
-- The CXX compiler identification is MSVC 19.16.27025.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: H:/projects/hunter/_Base/36fbf68/2413e11/3648706/Build/Qt/__qtbase/Build
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 1/11/2019 3:06:20 PM.
Project "H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\ALL_BUILD.vcxproj" (1) is building "H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Debug\ZERO_CHECK\".
  Creating directory "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\".
InitializeBuildStatus:
  Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Checking Build System
  CMake does not need to re-run because H:/projects/hunter/_Base/36fbf68/2413e11/3648706/Build/Qt/__qtbase/Build/CMakeFiles/generate.stamp is up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\ZERO_CHECK.vcxproj" (default targets).
Project "H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\ALL_BUILD.vcxproj" (1) is building "H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Debug\Qt-qtbase\".
  Creating directory "x64\Debug\Qt-qtbase\Qt-qtbase.tlog\".
InitializeBuildStatus:
  Creating "x64\Debug\Qt-qtbase\Qt-qtbase.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ComputeCustomBuildOutput:
  Creating directory "H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\Qt-qtbase-prefix\src\Qt-qtbase-stamp\Debug\".
  Creating directory "H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\CMakeFiles\Debug\".
CustomBuild:
  Creating directories for 'Qt-qtbase'
  Building Custom Rule H:/projects/hunter/_Base/36fbf68/2413e11/3648706/Build/Qt/__qtbase/CMakeLists.txt
  CMake does not need to re-run because H:/projects/hunter/_Base/36fbf68/2413e11/3648706/Build/Qt/__qtbase/Build/CMakeFiles/generate.stamp is up-to-date.
  Performing download step for 'Qt-qtbase'
  skip download
  No update step for 'Qt-qtbase'
  No patch step for 'Qt-qtbase'
  Performing configure step for 'Qt-qtbase'
  **********************************************************************
  ** Visual Studio 2017 Developer Command Prompt v15.9.4
  ** Copyright (c) 2017 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x64'
  
  Building Qt component:
    qtbase
  
  Dependent components:
  
  
  Components to skip:
    qt3d
    qtactiveqt
    qtandroidextras
    qtcanvas3d
    qtcharts
    qtconnectivity
    qtdatavis3d
    qtdeclarative
    qtdoc
    qtdocgallery
    qtenginio
    qtfeedback
    qtgamepad
    qtgraphicaleffects
    qtimageformats
    qtlocation
    qtmacextras
    qtmultimedia
    qtnetworkauth
    qtpim
    qtpurchasing
    qtqa
    qtquick1
    qtquickcontrols
    qtquickcontrols2
    qtremoteobjects
    qtrepotools
    qtscript
    qtscxml
    qtsensors
    qtserialbus
    qtserialport
    qtspeech
    qtsvg
    qtsystems
    qttools
    qttranslations
    qtvirtualkeyboard
    qtwayland
    qtwebchannel
    qtwebengine
    qtwebsockets
    qtwebview
    qtwinextras
    qtx11extras
    qtxmlpatterns
  
  
  Calculating list of files...
  Done
  Clean-up...
  removing: qtbase/qmake/Makefile
  removing: qtbase/qmake/Makefile
  removing: qtbase/qmake/makefile.obj
  removing: qtbase/qmake/makefiledeps.obj
  Qt configure command: configure.bat;-confirm-license;-nomake;examples;-nomake;tests;-opensource;-platform;win32-msvc2017;-static;-prefix;H:/projects/hunter/_Base/36fbf68/2413e11/3648706/Build/Qt/__qtbase/Install;-no-sql-db2;-no-sql-ibase;-no-sql-mysql;-no-sql-oci;-no-sql-odbc;-no-sql-psql;-no-sql-sqlite2;-no-sql-tds;-no-fontconfig;-no-gif;-no-icu;-no-openssl;-qt-freetype;-qt-harfbuzz;-qt-libjpeg;-qt-libpng;-qt-pcre;-qt-zlib;-debug-and-release;-skip;qt3d;-skip;qtactiveqt;-skip;qtandroidextras;-skip;qtcanvas3d;-skip;qtcharts;-skip;qtconnectivity;-skip;qtdatavis3d;-skip;qtdeclarative;-skip;qtdoc;-skip;qtdocgallery;-skip;qtenginio;-skip;qtfeedback;-skip;qtgamepad;-skip;qtgraphicaleffects;-skip;qtimageformats;-skip;qtlocation;-skip;qtmacextras;-skip;qtmultimedia;-skip;qtnetworkauth;-skip;qtpim;-skip;qtpurchasing;-skip;qtqa;-skip;qtquick1;-skip;qtquickcontrols;-skip;qtquickcontrols2;-skip;qtremoteobjects;-skip;qtrepotools;-skip;qtscript;-skip;qtscxml;-skip;qtsensors;-skip;qtserialbus;-skip;qtserialport;-skip;qtspeech;-skip;qtsvg;-skip;qtsystems;-skip;qttools;-skip;qttranslations;-skip;qtvirtualkeyboard;-skip;qtwayland;-skip;qtwebchannel;-skip;qtwebengine;-skip;qtwebsockets;-skip;qtwebview;-skip;qtwinextras;-skip;qtx11extras;-skip;qtxmlpatterns
  + cd qtbase
  + H:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\configure.bat -top-level -confirm-license -nomake examples -nomake tests -opensource -platform win32-msvc2017 -static -prefix H:/projects/hunter/_Base/36fbf68/2413e11/3648706/Build/Qt/__qtbase/Install -no-sql-db2 -no-sql-ibase -no-sql-mysql -no-sql-oci -no-sql-odbc -no-sql-psql -no-sql-sqlite2 -no-sql-tds -no-fontconfig -no-gif -no-icu -no-openssl -qt-freetype -qt-harfbuzz -qt-libjpeg -qt-libpng -qt-pcre -qt-zlib -debug-and-release -skip qt3d -skip qtactiveqt -skip qtandroidextras -skip qtcanvas3d -skip qtcharts -skip qtconnectivity -skip qtdatavis3d -skip qtdeclarative -skip qtdoc -skip qtdocgallery -skip qtenginio -skip qtfeedback -skip qtgamepad -skip qtgraphicaleffects -skip qtimageformats -skip qtlocation -skip qtmacextras -skip qtmultimedia -skip qtnetworkauth -skip qtpim -skip qtpurchasing -skip qtqa -skip qtquick1 -skip qtquickcontrols -skip qtquickcontrols2 -skip qtremoteobjects -skip qtrepotools -skip qtscript -skip qtscxml -skip qtsensors -skip qtserialbus -skip qtserialport -skip qtspeech -skip qtsvg -skip qtsystems -skip qttools -skip qttranslations -skip qtvirtualkeyboard -skip qtwayland -skip qtwebchannel -skip qtwebengine -skip qtwebsockets -skip qtwebview -skip qtwinextras -skip qtx11extras -skip qtxmlpatterns
   
  Notice: re-mapping requested qmake spec to unified 'win32-msvc'. 
   
  Bootstrapping qmake ...
  
  Microsoft (R) Program Maintenance Utility Version 14.16.27025.1
  Copyright (C) Microsoft Corporation.  All rights reserved.
  
  	cl -Yuqmake_pch.h -FIqmake_pch.h -Fpqmake_pch.pch -c -Fo./ -Fdqmake.pdb  -W2 -nologo -O1  /MP /wd4577   -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\qmake -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\qmake\library -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\qmake\generators -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\qmake\generators\unix -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\qmake\generators\win32 -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\qmake\generators\mac  -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase/include -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase/include\QtCore -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase/include\QtCore\5.11.1 -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase/include\QtCore\5.11.1\QtCore  -I..\src\corelib\global  -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\mkspecs\win32-msvc   -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS  -DQT_VERSION_STR=\"5.11.1\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=11 -DQT_VERSION_PATCH=1  -DQT_BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL  -DQT_NO_FOREACH -DUNICODE  H:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\qmake\generators\makefile.cpp H:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\qmake\generators\makefiledeps.cpp 
  makefile.cpp
  makefiledeps.cpp
  	cl -Yuqmake_pch.h -FIqmake_pch.h -Fpqmake_pch.pch -c -Fo./ -Fdqmake.pdb  -W2 -nologo -O1  /MP /wd4577   -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\qmake -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\qmake\library -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\qmake\generators -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\qmake\generators\unix -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\qmake\generators\win32 -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\qmake\generators\mac  -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase/include -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase/include\QtCore -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase/include\QtCore\5.11.1 -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase/include\QtCore\5.11.1\QtCore  -I..\src\corelib\global  -IH:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\mkspecs\win32-msvc   -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS  -DQT_VERSION_STR=\"5.11.1\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=11 -DQT_VERSION_PATCH=1  -DQT_BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL  -DQT_NO_FOREACH -DUNICODE  H:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\src\corelib\global\qrandom.cpp 
  qrandom.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1271): error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior. [H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1291): note: see reference to class template instantiation 'std::_Aligned<5004,64,double,false>' being compiled
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1298): note: see reference to class template instantiation 'std::_Aligned<5004,64,int,false>' being compiled
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1305): note: see reference to class template instantiation 'std::_Aligned<5004,64,short,false>' being compiled
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1312): note: see reference to class template instantiation 'std::_Aligned<5004,64,char,false>' being compiled
  H:\projects\hunter\_Base\36fbf68\2413e11\3648706\QtBuild\14\qtbase\src\corelib\global\qrandom.cpp(402): note: see reference to class template instantiation 'std::aligned_storage<5004,64>' being compiled
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.EXE"' : return code '0x2' [H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj]
  Stop.
  CMake Error at qt-configure.cmake:368 (message):
    Qt configure failed: 1
  
  
Done Building Project "H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj" (default targets) -- FAILED.
Done Building Project "H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

"H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\ALL_BUILD.vcxproj" (default target) (1) ->
"H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj" (default target) (3) ->
(CustomBuild target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1271): error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior. [H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj]
  NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.EXE"' : return code '0x2' [H:\projects\hunter\_Base\36fbf68\2413e11\3648706\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj]

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:02:38.59
-- Configuring incomplete, errors occurred!
See also "H:/projects/clean-editor/build64/CMakeFiles/CMakeOutput.log".

**Comment by ruslo** [comment]
This issue will be closed because the required template file [ISSUE_TEMPLATE.md][1] was ignored. Please read and fill carefully all parts of this file while submitting a bug report.

Thanks for understanding.

[1]: https://raw.githubusercontent.com/ruslo/hunter/master/.github/ISSUE_TEMPLATE.md
